Login = "gfkal"
Host = "users.deterlab.net"
Project = "SAFER"
Experiment = "DISSENT-CS2"
Phys = ["server-0.DISSENT-CS2.SAFER.isi.deterlab.net", "server-1.DISSENT-CS2.SAFER.isi.deterlab.net", "server-2.DISSENT-CS2.SAFER.isi.deterlab.net", "server-3.DISSENT-CS2.SAFER.isi.deterlab.net"]
Virt = ["10.255.0.1", "10.255.0.2", "10.255.0.3", "10.255.0.4"]
ProxyAddress = "localhost"
MonitorAddress = "users.isi.deterlab.net"
MonitorPort = 10000
Servers = 4
Simulation = "JVSS"
Hosts = 8
Debug = 1
RunWait = 0
