Login = "gfkal"
Host = "users.deterlab.net"
Project = "SAFER"
Experiment = "RandHerdSM3"
ProxyAddress = "localhost"
MonitorAddress = "users.isi.deterlab.net"
MonitorPort = 10000
Servers = 10
Simulation = "SkipCert"
Hosts = 0
Debug = 0
RunWait = 0
