Login = "gfkal"
Host = "users.deterlab.net"
Project = "SAFER"
Experiment = "RandHerdSM3"
Phys = ["server-0.RandHerdSM3.SAFER.isi.deterlab.net", "server-1.RandHerdSM3.SAFER.isi.deterlab.net", "server-2.RandHerdSM3.SAFER.isi.deterlab.net", "server-3.RandHerdSM3.SAFER.isi.deterlab.net", "server-4.RandHerdSM3.SAFER.isi.deterlab.net", "server-5.RandHerdSM3.SAFER.isi.deterlab.net", "server-6.RandHerdSM3.SAFER.isi.deterlab.net", "server-7.RandHerdSM3.SAFER.isi.deterlab.net", "server-8.RandHerdSM3.SAFER.isi.deterlab.net", "server-9.RandHerdSM3.SAFER.isi.deterlab.net"]
Virt = ["10.255.0.1", "10.255.0.2", "10.255.0.3", "10.255.0.4", "10.255.0.5", "10.255.0.6", "10.255.0.7", "10.255.0.8", "10.255.0.9", "10.255.0.10"]
ProxyAddress = "localhost"
MonitorAddress = "users.isi.deterlab.net"
MonitorPort = 10000
Servers = 10
Simulation = "SkipCert"
Hosts = 50
Debug = 3
RunWait = 0
